# url: https://y7kim.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Cloud Compass Computing Inc.
email: swcurran@cloudcompass.ca

description: "Cloud Compass Computing has been implementing end-to-end value
stream optimizations, integrating Development and Operations teams (DevOps), and
creating continuous improvement cultures for more than 15 years. We have been
contributing to the Linux Foundation’s Hyperledger Indy and Aries projects for
more than two years. In that work, we've dug deeply into self-sovereign identity
(SSI), decentralized identifiers (DIDs), verifiable credentials (VCs) and the
blockchain technologies that will drive the next major wave of Internet
innovation."


# Team names, titles and social links
people:
- name: Stephen Curran
  pic: 1
  position: Technical Architect and Biz/Tech Line Walker
  social:
    - title: twitter
      url: http://twitter.com/scurranC3I
    - title: github
      url: http://github.com/swcurran

- name: Shea Phillips
  pic: 2
  position: Technical Architect and Incredible Bit-Twiddler
  social:
    - title: github
      url: http://github.com/sheaphillips

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/scurranC3I
  - title: github
    url: http://github.com/cloudcompass
  - title: github
    url: http://github.com/swcurran

# Postal address (add as many lines as necessary)
address:
  - line: Victoria, British Columbia, Canada

# Build settings
markdown: kramdown
permalink: pretty