# url: https://y7kim.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Cloud Compass Computing, Inc.
email: swcurran@cloudcompass.ca
description: "Cloud Compass Computing, Inc. (C3I for short) is a boutique consultancy based in Victoria, British Columbia that has deep experience in DevOps and DevOps Transformation. C3I played a key role in the development of the Continuous Service Improvement Lab at the Province of British Columbia, a highly successful experiment in organizational and technical transformation from the Legacy to Agile/DevOps world of Digital Service Delivery."


# Team names, titles and social links
people:
- name: Stephen Curran
  pic: 1
  position: Technical Architect
  social:
    - title: twitter
      url: http://twitter.com/scurranC3I
    - title: github
      url: http://github.com/swcurran

- name: Shea Phillips
  pic: 2
  position: Technical Architect and Incredible Bit-Twiddler
  social:
    - title: github
      url: http://github.com/sheaphillips

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/scurranC3I
  - title: github
    url: http://github.com/cloudcompass

# Postal address (add as many lines as necessary)
address:
  - line: Victoria, British Columbia, Canada

# Build settings
markdown: kramdown
permalink: pretty